// modules/city/mappings/buildingBindings.ts
import { StaticBindingMeta } from './type';

export const BUILDING_BINDINGS_STATIC: Record<string, StaticBindingMeta> = {
  Building_E001: {
    id: 'Building_E001',
    label: 'Food Market',
    description: 'Groceries & takeout against your food budget.',
    rating: 4,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'Budget left', iconKey: 'utensils', defaultValue: 'R0' },
    upgrade: { label: 'Optimize basket', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'Manage Groceries', link: '/budgets?c=groceries' },
    effects: [
      { iconKey: 'coins', label: 'Spend MTD', tone: 'neg' },
      { iconKey: 'coins', label: 'Budget', tone: 'pos' },
      { iconKey: 'chart', label: 'Visits (7d)', tone: 'warn' },
    ],
    dataKeys: [
      'spend_mtd:groceries',
      'budget:groceries',
      'visits_7d:groceries', // distinct tx days or merchant visits
      'budget_left:groceries',
    ],
  },

  Building_C001: {
    id: 'Building_C001',
    label: 'Bank',
    description: 'Live income vs expense with net position and trends.',
    rating: 5,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'Net', iconKey: 'coins' },
    upgrade: { label: 'Automate saving', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'View Transactions', link: '/transactions' },
    effects: [
      { iconKey: 'chart', label: 'Income', tone: 'pos' },
      { iconKey: 'bolt',  label: 'Expenses', tone: 'neg' },
      { iconKey: 'bell',  label: 'Alerts', tone: 'warn' },
    ],
    dataKeys: [
      'income_mtd',
      'expenses_mtd',
      'alerts_count',
      'net_mtd',
    ],
  },

  Large_Apartments: {
    id: 'Large_Apartments',
    label: 'Library',
    description: 'Boost knowledge with short lessons and quizzes to earn XP.',
    rating: 4,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'XP potential', iconKey: 'book', defaultValue: '+0 XP' },
    upgrade: { label: 'Unlock module', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'Continue Learning', link: '/learn' },
    effects: [
      { iconKey: 'book',  label: 'Lessons',  tone: 'pos' },
      { iconKey: 'chart', label: 'Quiz avg', tone: 'pos' },
      { iconKey: 'bolt',  label: 'Day streak', tone: 'pos' },
    ],
    dataKeys: ['lessons_count', 'quiz_avg', 'learn_streak', 'xp_potential'],
  },

  Building_F003: {
    id: 'Building_F003',
    label: 'Hospital',
    description: 'Track your financial health and risk. Keep your Health EF topped up.',
    rating: 4,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'Health score', iconKey: 'heart', defaultValue: '—' },
    upgrade: { label: 'Improve score', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'View Health Finances', link: '/goals?tag=health' },
    effects: [
      { iconKey: 'coins',  label: 'Medical cashback', tone: 'pos' },
      { iconKey: 'bolt',   label: 'Spend MTD',       tone: 'neg' },
      { iconKey: 'shield', label: 'Health EF',       tone: 'pos' },
    ],
    dataKeys: ['medical_cashback_mtd', 'spend_mtd:health', 'health_ef_pct', 'health_score'],
  },

  Building_G004: {
    id: 'Building_G004',
    label: 'Residences',
    description: 'Home & personal care spending overview.',
    rating: 3,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'Home+Care MTD', iconKey: 'home', defaultValue: 'R0' },
    upgrade: { label: 'Reduce utilities', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'Tune Home & Care', link: '/budgets?c=home,personal' },
    effects: [
      { iconKey: 'coins', label: 'Home',        tone: 'neg' },
      { iconKey: 'coins', label: 'Personal',    tone: 'neg' },
      { iconKey: 'chart', label: 'Income share', tone: 'warn' },
    ],
    dataKeys: ['spend_mtd:home', 'spend_mtd:personal', 'income_share:home_personal', 'home_personal_mtd'],
  },

  Building_G005: {
    id: 'Building_G005',
    label: 'Residences',
    description: 'Track trend vs last month and top up repairs.',
    rating: 3,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'Trend', iconKey: 'chart', defaultValue: '0%' },
    upgrade: { label: 'Top up fund', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'Top Up Repairs', link: '/goals?tag=repairs' },
    effects: [
      { iconKey: 'coins',  label: 'Home',         tone: 'neg' },
      { iconKey: 'coins',  label: 'Personal',     tone: 'neg' },
      { iconKey: 'shield', label: 'Repairs top-up', tone: 'pos' },
    ],
    dataKeys: ['spend_mtd:home', 'spend_mtd:personal', 'repairs_topup', 'trend_vs_last_month:home_personal', 'trend_headline'],
  },

  Building_G001: {
    id: 'Building_G001',
    label: 'Residences',
    description: 'Daily utilities and off-peak usage.',
    rating: 3,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'Avg/day', iconKey: 'bolt', defaultValue: 'R0' },
    upgrade: { label: 'Hit 4 off-peak', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'Utilities Tips', link: '/learn/utilities' },
    effects: [
      { iconKey: 'chart',  label: 'Water',        tone: 'warn' },
      { iconKey: 'bolt',   label: 'Off-peak days', tone: 'pos' },
      { iconKey: 'shield', label: 'Tips',         tone: 'pos' },
    ],
    dataKeys: ['utilities_avg_per_day', 'water_trend_pct', 'offpeak_days_7d'],
  },

  Office_2: {
    id: 'Office_2',
    label: 'Civic Offices',
    description: 'All your active goals and completion rates.',
    rating: 4,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'Completion', iconKey: 'chart', defaultValue: '0%' },
    upgrade: { label: 'Boost auto-save', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'Manage Goals', link: '/goals' },
    effects: [
      { iconKey: 'chart', label: 'Active goals', tone: 'pos' },
      { iconKey: 'coins', label: 'Auto-contrib', tone: 'pos' },
      { iconKey: 'bolt',  label: 'Streak',       tone: 'pos' },
    ],
    dataKeys: ['goals_active', 'auto_contrib_mtd', 'goal_streak_weeks', 'goals_completion_pct'],
  },

  Building_D001: {
    id: 'Building_D001',
    label: 'Police Station',
    description: 'Anomalies, impulse buys and overspending warnings.',
    rating: 5,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'Alerts', iconKey: 'bell', defaultValue: '0' },
    upgrade: { label: 'Tighten rules', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'Review Anomalies', link: '/insights/anomalies' },
    effects: [
      { iconKey: 'bell',  label: 'Anomalies',    tone: 'warn' },
      { iconKey: 'bolt',  label: 'Impulse (7d)', tone: 'warn' },
      { iconKey: 'coins', label: 'Over-budget',  tone: 'neg' },
    ],
    dataKeys: ['alerts_count', 'impulse_7d', 'overbudget_count'],
  },

  Building_B001: {
    id: 'Building_B001',
    label: 'Hotel',
    description: 'Lifestyle, entertainment and subscription spending.',
    rating: 4,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'Lifestyle MTD', iconKey: 'coins', defaultValue: 'R0' },
    upgrade: { label: 'Trim subs', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'Manage Lifestyle', link: '/budgets?c=lifestyle' },
    effects: [
      { iconKey: 'coins',  label: 'Entertainment', tone: 'neg' },
      { iconKey: 'coins',  label: 'Subscriptions', tone: 'neg' },
      { iconKey: 'shield', label: 'Cancel target', tone: 'pos' },
    ],
    dataKeys: ['spend_mtd:entertainment', 'spend_mtd:subscriptions', 'lifestyle_mtd', 'subs_cancel_target'],
  },

  BARRA_CAFE_AL_PASO: {
    id: 'BARRA_CAFE_AL_PASO',
    label: 'Café',
    description: 'See friends, challenges and community momentum.',
    rating: 5,
    level: { current: 1, max: 3 },
    sizeLabel: '5×5',
    headline: { label: 'Friends active', iconKey: 'users', defaultValue: '0' },
    upgrade: { label: 'Invite friends', coins: 44, xp: 25, cost: '—' },
    cta: { label: 'Open Community', link: '/community' },
    effects: [
      { iconKey: 'users', label: 'Active (7d)', tone: 'pos' },
      { iconKey: 'chart', label: 'Challenges',  tone: 'pos' },
      { iconKey: 'coins', label: 'Likes',       tone: 'pos' },
    ],
    dataKeys: ['friends_active_7d', 'challenges_active', 'likes_recent'],
  },
};
