import express from 'express';
import multer from 'multer';
import fs from 'fs/promises';
import path from 'path';
import { spawn } from 'child_process';
import axios from 'axios';
import pool from '../../../config/db';
import { logger } from '../../../config/logger';
import { getCategories, createTransaction, getTransaction } from '../../transactions/services/transaction.service';
import { cp } from 'fs';
import { ExtractorContext } from '../strategies/strategy_context';

const upload = multer({ dest: '/tmp/uploads' });
const router = express.Router();

// run an external process and await its exit
export function runProcess(cmd: string, args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args);
    proc.stdout.on('data', d => console.log(`[extractor stdout]`, d.toString()));
    proc.stderr.on('data', d => console.error(`[extractor stderr]`, d.toString()));
    proc.once('error', reject);
    proc.once('exit', code => {
      if (code === 0) resolve();
      else reject(new Error(`Extractor exited with code ${code}`));
    });
  });
}

// STEP 1: upload → extract → classify → preview
router.post('/upload-statement', upload.single('statement'), async (req, res) => {
  const file = req.file, password = req.body.password || '', accountId = req.body.accountId, bankName = req.body.bankName;
  if (!file || !accountId) {
    res.status(400).json({ error: 'Missing file or accountId' });
    return;
  }

  try {
    // 1. extract
    const extractor = new ExtractorContext(bankName);
    const outPath   = '/tmp/transactions.json';
    await extractor.extract(file.path, outPath, password);

    // 2. load raw
    const transactions = JSON.parse(await fs.readFile('/tmp/transactions.json', 'utf8'));
    logger.info(`Extracted ${transactions.length} transactions from ${file.originalname}`);

    // 3. classify
    const { data } = await axios.post('http://localhost:6000/predict-batch', { transactions });
    const results = data as Array<{ category: string; source: string }>;
    if (!Array.isArray(results) || results.length !== transactions.length) {
      logger.error('Classifier mismatch', { expected: transactions.length, got: results.length });
      res.status(500).json({ error: 'Classifier returned wrong length' });
      return;
    }

    const categories = await getCategories();
    
    logger.info(`Classification results ${ results.length }`);
    if(results.length === 0) {
      logger.warn('No transactions classified, returning empty preview');
      res.status(400).json({ error: 'No transactions identified' });
      return;
    }

    // 4. preview for UI
    const preview = transactions.map((t: any, i: number) => {
      interface Transaction {
        direction: string;
        amount: number;
        description: string;
        date: string;
        [key: string]: any;
      }

      interface ClassificationResult {
        category: string;
        source: string;
      }

      interface Category {
        category_id: number;
        category_name: string;
        [key: string]: any;
      }

      const match: Category | undefined = categories.find(
        (c: Category) => c.category_name === (results[i] as ClassificationResult).category.toLowerCase()
      );
      // add custom category ID if it exists, otherwise default to 4
      const id = match ? match.category_id : 4;
      return {
        accountId,
        ...t,
        predicted_category: results[ i ].category,
        classification_source: results[ i ].source,
        category_id: id
      };
    });

    logger.info(`Generated preview for review ${preview.length }`);
    res.json({ preview });
  } catch (err) {
    logger.error('Pipeline error', err);
    res.status(500).json({ error: 'Failed to process statement' });
  }
});

router.post('/feedback', async (req, res) => {
  const { feedback } = req.body as { feedback: Array<{ transactionId: number; categoryId: number }> };
  if (!Array.isArray(feedback)) {
    res.status(400).json({ error: 'Missing feedback array' });
    return;
  }

  try {
    const { data } = await axios.post('http://localhost:6000/feedback-train', { feedback });
    const feedbackResponse = data as { status: string };
    res.json({ status: feedbackResponse.status });
    logger.info(`Feedback processed, retraining started: ${feedbackResponse.status}`);
  } catch (err) {
    logger.error('Feedback processing error', err);
    res.status(500).json({ error: 'Failed to process feedback' });
  }
})

export interface Transaction {
  transaction_id?: number;  // Optional, auto-generated by DB
  account_id: number;
  category_id?: number;  // Optional if using custom_category_id
  custom_category_id?: number;  // Optional if using category_id
  transaction_amount: number;
  transaction_type: 'expense' | 'income' | 'transfer' | 'fee' | 'withdrawal' | 'deposit';
  transaction_name: string;  // Name or description of the transaction
  transaction_date: string;  // ISO date string format (YYYY-MM-DD)
  is_recurring?: boolean;
  linked_goal_id?: number;
  linked_challenge_id?: number;
  budget_id?: number;
  points_awarded?: number;
}

// STEP 2: confirm → persist
router.post('/confirm-statement', async (req, res) => {
  const { preview, recurringFlags } = req.body as {
    preview: Array<any>;
    recurringFlags?: boolean[];
  };

  if (!Array.isArray(preview)) {
    res.status(400).json({ error: 'Missing preview array' });
    return;
  }

  try {
  // 1) turn each "preview" item into your Transaction DTO
    const txns: Transaction[] = preview.map((t, i) => {
      let transaction_type: Transaction['transaction_type'];
      if (t.direction === 'out')       transaction_type = 'expense';
      else if (t.direction === 'in')    transaction_type = 'income';
      else if (t.direction === 'transfer') transaction_type = 'transfer';
      else throw new Error(`Invalid direction ${t.direction}`);

      // add goal, budget and challenge IDs if they exist

      return {
        account_id:       t.accountId,
        category_id:      t.category_id,
        transaction_amount: Math.abs(t.amount) ? Math.abs(t.amount) : 0,
        transaction_type,
        transaction_name: t.description,
        transaction_date: t.date,
        is_recurring:     recurringFlags?.[i] ?? false,
        points_awarded:   0,
      };
    });

    // 2) call your service for each, in parallel
    const results = await Promise.all(
      txns.map(txn => createTransaction(txn))
    );

    // 3) send back the array of inserted rows (each has transaction_id & updated_balance)
    res.json({ transactions: results });    
  } catch (err) {
    logger.error('DB insert error', err);
    res.status(500).json({ error: 'Failed to save transactions' });
  }
});

export default router;