# .github/workflows/frontend-tests.yml
name: Frontend Unit Tests

on:
  push:
    branches: [main, testing]
    paths:
      - 'gamified-finance-frontend/**'
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    branches: [main, testing]
    paths:
      - 'gamified-finance-frontend/**'

jobs:
  test-frontend:
    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.2'

      - name: Install dependencies
        working-directory: ./gamified-finance-frontend
        run: npm ci

      - name: Run unit tests
        working-directory: ./gamified-finance-frontend
        run: npm run test
