name: Backend Integration Tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

permissions:
  contents: read

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PASETO_LOCAL_KEY: ${{ secrets.PASETO_LOCAL_KEY }}
      NODE_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run integration tests with coverage
        run: npm run test:int

      - name: Upload integration coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-integration-coverage
          path: coverage/

      - name: Integration tests finished
        run: echo "Integration test run completed"
